### ISSUE TITLE
Warning about license violation!

### ISSUE THREAD

**Issue by volkanceylan** [Pushan12/transac#1]

**Comment by Serenis** [comment]
Hello,
 
We noticed that you have public forks of StartSharp generated code in following repositories:
 
https://github.com/Pushan12/OneHospital

StartSharp has a commercial license, and it doesn't allow redistribution in source code form.
 
We kindly ask you to delete these forks, remove any StartSharp code you have ASAP, before contacting GitHub and taking further legal action.
 
Serenity Team

**Comment by Pushan12** [comment]
Hello,
As per your request I have removed the following repository
https://github.com/Pushan12/OneHospital
